Created GetAnalysisStatus Page
uw-ssec/genetic-forensic-portal pull request #31
Opened 2024-05-07 20:35 UTC by IshikaKhandelwal

2024-05-08 17:29 UTC, nikiburggraf requested changes
Overall good, please take a look at some suggestions I have :)

2024-05-08 17:29 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +st.title("Analysis Status Checker")
For now, let's have this be consistent with the filename/URL of the page

```suggestion
st.title("Get Analysis Status")
```

2024-05-08 17:29 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +    client.list_completed_analyses(),
I'm wondering if we should refactor the name of this method since it's returning incomplete analyses now. What do you think?

2024-05-08 17:29 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/client/gf_api_client.py
> +def get_analysis_status(sample_id: str | None) -> str:
Doesn't make a ton of sense to accept a `None` value for `sample_id` here, so it's fine to just remove it

```suggestion
def get_analysis_status(sample_id: str) -> str:
```

2024-05-08 17:29 UTC, nikiburggraf commented on tests/app/client/test_gf_api_client.py
> +        client.get_analysis_status(None)
If changing the `get_analysis_status` parameters to not accept `None` is getting you errors on this line, you can get the linter to ignore that by adding this comment here:

```suggestion
        client.get_analysis_status(None) # type: ignore[arg-type]
```

2024-05-08 17:29 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +        st.error(f"An unexpected error occurred: {e!s}")
I think this type conversion may be unnecessary

```suggestion
        st.error(f"An unexpected error occurred: {e}")
```

2024-05-09 00:01 UTC, IshikaKhandelwal commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +    client.list_completed_analyses(),
I agree, since now we have In-progress and failed UIUD's it makes sense to refactor the name, something like `list_analysis_uiuds`?

2024-05-09 16:53 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +    client.list_completed_analyses(),
Maybe `list_analyses` instead?

2024-05-09 18:50 UTC, IshikaKhandelwal commented on src/genetic_forensic_portal/app/pages/5_Get_Analysis_Status.py
> +    client.list_completed_analyses(),
Yes perfect!

2024-05-13 18:44 UTC, nikiburggraf approved these changes
Thank you for your changes! This all looks great to me!

2024-05-13 21:18 UTC, merged