feat: Added GetAllAnalysis page
uw-ssec/genetic-forensic-portal pull request #47
Opened 2024-05-29 01:40 UTC by IshikaKhandelwal

2024-05-29 02:03 UTC, IshikaKhandelwal commented
Hi Niki! Do you have any suggestions for improving the codecov coverage? Thanks!

2024-06-04 22:38 UTC, nikiburggraf requested changes
Looks pretty good! Just a comment about changing up the output of the `get_all_analyses` call :)

Lemme know if you need/want help dealing with rebasing my changes

2024-06-04 22:38 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/client/gf_api_client.py
> +    results: dict[str, Any] = {}
Maybe instead of a dict, you could try creating a `get_analyses_response.py` object like this one that I made for the ListAnalysis page: https://github.com/uw-ssec/genetic-forensic-portal/blob/main/src/genetic_forensic_portal/app/client/models/list_analyses_response.py

That PR is (finally) merged now, so if you rebase your changes, you can find a place to put this new file under `app/client/model/`

2024-06-04 22:38 UTC, nikiburggraf commented on src/genetic_forensic_portal/app/pages/7_Get_All_Analysis.py
nit: change filename to `7_Get_All_Analyses.py`

2024-06-11 20:34 UTC, nikiburggraf approved these changes

2024-06-11 20:34 UTC, merged